/** Seeded onboarding template — send route advances contracted → active when this id is used. */
export const SEED_ONBOARDING_TEMPLATE_ID = 'b2c3d4e5-f6a7-4901-bcde-f12345678901'

/** Path segment for preview URLs (not a valid JWT). Replaced with a real portal URL on send. */
export const CAPABILITIES_LINK_PREVIEW_TOKEN = '__crm_capabilities_preview__'

/**
 * Shown in template render + send review UI instead of a real or preview URL.
 * Replaced with the minted portal link on send (`injectCapabilitiesIntoEmail`).
 */
export const CAPABILITIES_LINK_DISPLAY_SENTINEL = '{capabilities_link_autogenerated_on_send}'

/** `shop` query value for preview URLs (not a real location id). Replaced on send. */
export const EXPERT_ASSIST_LINK_PREVIEW_SHOP_ID = '__crm_expert_assist_preview__'

/**
 * Shown in template render + send review UI instead of a real intake URL.
 * Replaced with the shop-specific intake link on send (`injectExpertAssistIntoEmail`).
 */
export const EXPERT_ASSIST_LINK_DISPLAY_SENTINEL = '{expert_assist_link_autogenerated_on_send}'

/**
 * Shown in template render + send review UI instead of a real enrollment-portal URL.
 * Replaced with the minted onboarding link on send (`injectEnrollmentPortalIntoEmail`).
 * Distinct from the capabilities link: same JWT, but the `/onboarding` surface.
 */
export const ENROLLMENT_PORTAL_LINK_DISPLAY_SENTINEL = '{enrollment_portal_link_autogenerated_on_send}'
